# Generated by Django 4.2 on 2023-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advusers',
            name='bank_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advusers',
            name='date_birth',
            field=models.DateTimeField(default='2000-01-01 10:00', verbose_name='Дата народження'),
        ),
    ]
