# Generated by Django 4.2 on 2023-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('active', models.BooleanField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Банер заднього фону',
            },
        ),
        migrations.CreateModel(
            name='Baners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('type_obj', models.CharField(max_length=255, verbose_name='Тип')),
                ('speed', models.SmallIntegerField(verbose_name='Швидкість обертання')),
                ('active', models.BooleanField(verbose_name='Статус')),
                ('trailerURL', models.URLField(blank=True, verbose_name='URL')),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
            },
        ),
    ]
