# Generated by Django 4.2 on 2023-05-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_rename_time_create_films_date_create'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва Сторінки')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Головна картинка')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.seo')),
            ],
        ),
        migrations.CreateModel(
            name='News_and_Evens',
            fields=[
                ('pages_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.pages')),
                ('videoURL', models.URLField(verbose_name='Відео')),
                ('date_publications', models.DateTimeField(verbose_name='Дата публікації')),
                ('type_object', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            bases=('frontend.pages',),
        ),
    ]
