# Generated by Django 4.2 on 2023-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_pages_news_and_evens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_and_evens',
            name='date_publications',
            field=models.DateTimeField(default='2023-05-30 17:09', verbose_name='Дата публікації'),
        ),
    ]
