# Generated by Django 4.2 on 2023-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_news_and_evens_date_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_and_evens',
            name='date_publications',
            field=models.DateTimeField(verbose_name='Дата публікації'),
        ),
    ]
