# Generated by Django 4.2 on 2023-05-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='film',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
