# Generated by Django 4.2 on 2023-05-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-16 18:13', verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер залу')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
                ('schema_hall', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Схема залу')),
                ('photo_banner', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото банера')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.seo')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кінотеатр')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
                ('conditions', models.TextField(blank=True, verbose_name='Умови')),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Логотип')),
                ('photo_banner', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото банера')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('coordinates', models.CharField(max_length=255, verbose_name='Координати')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.seo')),
            ],
            options={
                'verbose_name': 'Кінотеатр',
                'verbose_name_plural': 'Кінотеатри',
                'ordering': ['name'],
            },
        ),
    ]
