# Generated by Django 4.2 on 2023-05-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='content',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='films',
            name='gallery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemas.gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='films',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinemas.seo'),
        ),
    ]
