# Generated by Django 4.2 on 2023-05-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_films_time_create_halls_cinemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinemas', verbose_name='Кінотеатр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halls',
            name='number',
            field=models.IntegerField(verbose_name='Номер залу'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
