# Generated by Django 4.2 on 2023-05-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
