# Generated by Django 4.2 on 2023-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_remove_cinemas_address_remove_cinemas_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='time_create',
            new_name='date_create',
        ),
    ]
