# Generated by Django 4.2 on 2023-05-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_alter_films_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='seo',
            field=models.OneToOneField(db_column='seo_key', on_delete=django.db.models.deletion.CASCADE, related_name='film_key', to='cinemas.seo'),
        ),
    ]
